-- Ejecucción de Consultas.  
-- REPORTES 
BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_22_B(:RESDATA, 2000); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_22_A(:RESDATA, 2000); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_D(:RESDATA, 2000); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_F(:RESDATA, 2000); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_G(:RESDATA, 2000); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_H(:RESDATA, 2000); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_I(:RESDATA, 2000); END;



-- VALIDAR DATOS PARA INSERTAR 

BEGIN OPERACION.PKG_OPERACION_LEO.SP_VALIDAR_DATOS_TBL_49A(); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_VALIDAR_DATOS_TBL_49C(); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_VALIDAR_DATOS_TBL_44C(); END;

-- insertar valores input tabla catalogo 

BEGIN OPERACION.PKG_OPERACION_LEO.SP_CARGA_TEMP_PPTO_INPUTS_49A( 'PROSAVI II' ); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_CARGA_TEMP_PPTO_INPUTS_49C( 'PROSAVI II' ); END;

BEGIN OPERACION.PKG_OPERACION_LEO.SP_CARGA_TEMP_PPTO_INPUTS_44C( 'PROSAVI II' ); END;



-- solo para limpiar si vuelves ejecutar 
/*
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.G.1'  
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.F.1'
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.D.1'
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.H.1'
*/


DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.F.1'


