--DROP TABLE OPERACION.TMP_CARGA_TBL_04APPTO20151_ CASCADE CONSTRAINTS;

CREATE TABLE OPERACION.TMP_CARGA_TBL_04APPTO20151_ 
(
	PERIODO	                     VARCHAR(50),
	VIGENTES_02MV	             VARCHAR(50),
	CREDITOS_MORA_TEMPRANA_36MV	 VARCHAR(50),
	VENCIDOS_6MV	             VARCHAR(50),
	TOTAL_VENCIDOS               VARCHAR(50),
	REO	                         VARCHAR(50)	,
	REO_COMERCIAL	             VARCHAR(50)	,
	COMERCIAL	                 VARCHAR(50)	,
	IRR	                         VARCHAR(50)	,
	LIQ_ACUMULADOS	             VARCHAR(50)	,
	TOTAL_CREDITOS	             VARCHAR(50)	,
	LIQ_NAT_CREDITOS_VIG	     VARCHAR(50)	,
	LIQ_ANTI_CREDITOS_VIG	     VARCHAR(50)	,
	PAGO_UNICO_DEUDOR	         VARCHAR(50)	,
	PAGO_UNICO_CESION	         VARCHAR(50)	,
	RESTRUCTURA_CORTOP	         VARCHAR(50)	,
	RESTRUCTURA_LARGOP	         VARCHAR(50)	,
	DACION	                     VARCHAR(50)	,
	VENTA_REO	                 VARCHAR(50)	,
	COM_V_REO_RES_NPL	         VARCHAR(50)	,
	TOTAL_RESOLUCIONES	         VARCHAR(50)	,
	UPB_REMANENTE_CVV	         VARCHAR(50)	,
	VAL_COLATERAL_CVV	         VARCHAR(50)	,
	VAL_COLATERAL_BIENES_ADJ	 VARCHAR(50)	,
	VAL_COLATERAL_REO_COMS	     VARCHAR(50)	,
	UPB_REMANENTE_CRE_COMS	     VARCHAR(50)
)
ORGANIZATION EXTERNAL
   (DEFAULT DIRECTORY DIR_PAC
       ACCESS PARAMETERS (
          RECORDS DELIMITED BY NEWLINE
          FIELDS
             TERMINATED BY ','
       )
    LOCATION ('04.A.PPTO20151.csv')); 	
    
