-- Ejecuccion de Consultas.  
-- REPORTES 
BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_22_B(:RESDATA, 2000); END; -- Antes ->Tiempo  4s

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_22_A(:RESDATA, 2000); END; -- Antes ->Tiempo 8 min  / Despues 32s

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_D(:RESDATA, 2000); END; -- Antes ->Tiempo 4 min    | Despues -> 4S

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_F(:RESDATA, 2000); END; -- Antes ->Tiempo 4 min    | Despues -> 3S

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_G(:RESDATA, 2000); END; -- Antes ->Tiempo 2.30 min | Despues -> 3S  

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_H(:RESDATA, 2000); END; -- Antes ->Tiempo 10 min   | Despues -> 6S

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_14_I(:RESDATA, 2000); END; -- Antes ->Tiempo 3 min    | Despues -> 6S 

BEGIN OPERACION.PKG_OPERACION_LEO.SP_INSERTHIST_4_A(:RESDATA, 1); END;  -- Antes ->Tiempo 3 min    | Despues -> 6S

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_4_A(:RESDATA, 1); END;  -- Antes ->Tiempo 3 min    | Despues -> 

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_4_B(:RESDATA, 1, 8); END;  -- Antes ->Tiempo 3 min    | Despues -> 10S 

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_4_D(:RESDATA, 1, 110); END;  -- Antes ->Tiempo 3 min    | Despues -> 10S

BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_4_E(:RESDATA, 1, 114); END;  -- Antes ->Tiempo 3 min    | Despues -> 10S



-- solo para limpiar si vuelves ejecutar 
/*
 DELETE FROM OPERACION.PPTO_PERIODO_BASECREDITOS WHERE NOMBRE_AGRUPADOR = '22.B.1';
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '22.A.1'
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.G.1'  
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.F.1'
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.D.1'
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.H.1'
DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.E.1'

DELETE  FROM OPERACION.PPTO_PRESUPUESTO_BY_TAG WHERE CLAVE_AGRUPADOR = '04.D.1'
DELETE  FROM OPERACION.PPTO_PRESUPUESTO_BY_TAG WHERE CLAVE_AGRUPADOR = '04.E.1'
*/

DELETE  FROM OPERACION.PPTO_PRESUPUESTO_BY_TAG WHERE CLAVE_AGRUPADOR = '04.E.1'

-- DELETE FROM OPERACION.PPTO_PRESUPUESTO_BY_GRUPO WHERE CLAVE_AGRUPADOR = '14.I.1'
