-- ID_CARGA 
BEGIN OPERACION.PKG_OPERACION_LEO.SP_VALIDAR_DATOS_04EPPTO2015(4); END;

-- RECIBE : ID_PRESUPUESTO, ID_CARGA 
BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_4_E( 1, 114); END;  -- Antes ->Tiempo 3 min    | Despues -> 10S

