-- Crear Tabla  pendupm.xtravelfieldhdr con su Indice
create table pendupm.xtravelfieldhdr as (
select *      
FROM xtravelfieldhdr@erpbase.com  A
);

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.xtravelfieldhdr TO PM_OPER;

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.xtravelfieldhdr TO TL_PM;


CREATE INDEX PENDUPM.INDEX_BATBNR_XT ON PENDUPM.xtravelfieldhdr
("BatNbr")
LOGGING
NOPARALLEL
COMPUTE STATISTICS;
 
-- Crear Tabla  pendupm.xAddDev con su indice

create table pendupm.xAddDev as (
select *   
FROM xAddDev@ERPBASE.COM A
);


GRANT SELECT ON PENDUPM.xAddDev TO COMERCIAL_OPER;

GRANT SELECT ON PENDUPM.xAddDev TO ODI;

GRANT SELECT ON PENDUPM.xAddDev TO OPERACION WITH GRANT OPTION;

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.xAddDev TO PM_OPER;

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.xAddDev TO TL_PM;


CREATE INDEX PENDUPM.INDEX_BATBNR_DEV ON PENDUPM.xAddDev
("BatNbr")
LOGGING
NOPARALLEL
COMPUTE STATISTICS;


-- Crear Tabla  pendupm.GLTRAN con su indice

create table pendupm.GLTRAN as (
select *      
FROM GLTRAN@ERPBASE.COM A
);

CREATE INDEX PENDUPM.INDEX_BATBNR ON PENDUPM.GLTRAN
("BatNbr")
LOGGING
NOPARALLEL
COMPUTE STATISTICS;

GRANT SELECT ON PENDUPM.GLTRAN TO COMERCIAL_OPER;

GRANT SELECT ON PENDUPM.GLTRAN TO ODI;

GRANT SELECT ON PENDUPM.GLTRAN TO OPERACION WITH GRANT OPTION;

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.GLTRAN TO PM_OPER;

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.GLTRAN TO TL_PM;


-- crear tabla maestra

create  table pendupm.iaal as (

select
gas.IDGASTO, MT.NMMOTIVOGASTO, gas.FDFECINI,gas.FDFECFIN,gas.FDFECREGISTRO,gas.IDSOLICITANTE,gas.FCSTATUS,gas.FNEMPNOMINA,gas.FCURGENTE,gas.FCVIATICO0
,sum(com.FNIMPORTE) FV_FNIMPORTE,sum(com.FNTOTAL) FV_FNTOTAL
,con.NMCONCEPTO ,con.IDTPOGASTO
,FA.IDGASTOMAIN ga_IDGASTOMAIN
,BI.IMPORTESOLICITUD BI_IMPORTESOLICITUD ,BI.IMPORTEFACTURACION BI_IMPORTEFACTURACION
,fm.FCSTATUS ga_FCSTATUS
,xt."BatNbr" xt_BatNbr ,xt."RefNbr" xt_RefNbr
,gl."CuryDrAmt" gl_CuryDrAmt
FROM
/*4678*/    PENDUPM.GASTOMAIN Gas                           
/*2466*/    left join PENDUPM.comprobaciongasto com on gas.idgasto = com.idgasto
/*2558*/    left join PENDUPM.conceptogasto con on com.IDTPOGASTO = con.IDTPOGASTO and com.IDCONCEPTO = con.IDCONCEPTO
/*2583*/    left join (SELECT IDGASTOMAIN,IDCONCEPTO,DECODE (IDCONCEPTO,  1043, 8,  1045, 7,0)IDTPOGASTO, SUM (FNIMPORTE) FNIMPORTE, IDPLANVIAJE FROM pendupm.facturaasignacion fa GROUP BY IDGASTOMAIN, IDCONCEPTO, IDPLANVIAJE) fa on  gas.idgasto =  fa.IDPLANVIAJE  and com.IDTPOGASTO =  fa.IDTPOGASTO
/*2583*/    left join (select solicitud, CONCEPTO1 , sum (IMPORTESOLICITUD) IMPORTESOLICITUD , sum(IMPORTEFACTURACION) IMPORTEFACTURACION from GASTOS_TMP_LAYOUT@pendubi.com BI group by solicitud, CONCEPTO1 ) bi on FA.IDCONCEPTO = bI.CONCEPTO1 AND FA.IDGASTOMAIN = BI.SOLICITUD         
/*2583*/    left join PENDUPM.FACTURACIONMAIN fm on FA.IDGASTOMAIN = fm.IDGASTOMAIN
/*2727*/    left join pendupm.xtravelfieldhdr xt on fm.IDGASTOMAIN = to_number(xt."ReqNbr")
/*2727*/    left join (select sum(gl."CuryDrAmt") "CuryDrAmt" , "BatNbr" , "RefNbr"from pendupm.GLTRAN gl  where gl."Acct" like '60100%' group by "BatNbr" , "RefNbr") gl on  gl."BatNbr" = xt."BatNbr" and gl."RefNbr" = xt."RefNbr"
            INNER JOIN PENDUPM.CTMOTIVOGASTO MT ON MT.IDMOTIVOGASTO = Gas.IDMOTIVOGASTO
WHERE

 gas.FDFECREGISTRO >= to_Date ( '2017/01/01' ,'yyyy/MM/dd')
and com.IDTPOGASTO  in (7,8)  --7,8

group by
gas.IDGASTO, MT.NMMOTIVOGASTO,  gas.FDFECINI,gas.FDFECFIN,gas.FDFECREGISTRO,gas.IDSOLICITANTE,gas.FCSTATUS,gas.FNEMPNOMINA,gas.FCURGENTE,gas.FCVIATICO0--com.IDGASTO ,FA.IDGASTOMAIN,
,con.NMCONCEPTO ,con.IDTPOGASTO
,FA.IDGASTOMAIN
,BI.IMPORTESOLICITUD  ,BI.IMPORTEFACTURACION
,fm.FCSTATUS
,xt."BatNbr",xt."RefNbr"
,gl."CuryDrAmt"
); 


GRANT SELECT ON PENDUPM.iaal TO COMERCIAL_OPER;

GRANT SELECT ON PENDUPM.iaal TO ODI;

GRANT SELECT ON PENDUPM.iaal TO OPERACION WITH GRANT OPTION;

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.iaal TO PM_OPER;

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.iaal TO TL_PM;
