-- RECIBE :  ID_CARGA 
BEGIN OPERACION.PKG_OPERACION_LEO.SP_VALIDAR_DATOS_04BPPTO2015(4); END;
-- RECIBE : ID_PRESUPUESTO, ID_CARGA 
BEGIN OPERACION.PKG_OPERACION_LEO.SP_REPORTE_4_B(1, 8); END;  -- Antes ->Despues -> 10S


