Insert into OPERACION.VMC_ETAPAS_TAREAS
   (ID_CASO, ID_TAREA, FECHA_REGISTRO, FECHA_FIN, ORIGEN, ID_PROC_VERIFICACION, JUICIO, ID_JUICIO, ID_ETAPA, ETAPA, NOMBRE_ETAPA, CREDITO, ID_ASIGNA, BANDEJA, FECHA_VERIFICADOR01, FECHA_FIN_VERIFICADOR01, FECHA_VERIFICADOR02, FECHA_FIN_VERIFICADOR02, FECHA_DICTAMEN, FECHA_FIN_DICTAMEN, ID_VERIFICADOR01, ID_VERIFICADOR02, ID_VERIFICADOR_DICTAMEN, RESULTADO_ETAPA_VER01, RAZON_ETAPA_VER01, RESULTADO_ETAPA_VER02, RAZON_ETAPA_VER02, RESULTADO_ETAPA_DICTAMEN, RAZON_ETAPA_DICTAMEN, COMENTARIO_VER01, COMENTARIO_VER02, COMENTARIO_DICTAMEN)
 Values
   (4499999, 112198, TO_DATE('12/20/2017 16:49:46', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    'QUASAR', 355861, '101402', 141418, 61, 
    '190', 'APELACION', '123455', 'JR', 'GRUPO', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);

Insert into OPERACION.VMC_ETAPAS_TAREAS
   (ID_CASO, ID_TAREA, FECHA_REGISTRO, FECHA_FIN, ORIGEN, ID_PROC_VERIFICACION, JUICIO, ID_JUICIO, ID_ETAPA, ETAPA, NOMBRE_ETAPA, CREDITO, ID_ASIGNA, BANDEJA, FECHA_VERIFICADOR01, FECHA_FIN_VERIFICADOR01, FECHA_VERIFICADOR02, FECHA_FIN_VERIFICADOR02, FECHA_DICTAMEN, FECHA_FIN_DICTAMEN, ID_VERIFICADOR01, ID_VERIFICADOR02, ID_VERIFICADOR_DICTAMEN, RESULTADO_ETAPA_VER01, RAZON_ETAPA_VER01, RESULTADO_ETAPA_VER02, RAZON_ETAPA_VER02, RESULTADO_ETAPA_DICTAMEN, RAZON_ETAPA_DICTAMEN, COMENTARIO_VER01, COMENTARIO_VER02, COMENTARIO_DICTAMEN)
 Values
   (4499998, 112197, TO_DATE('12/20/2017 13:26:22', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/20/2017 13:27:41', 'MM/DD/YYYY HH24:MI:SS'), 
    'QUASAR', 355860, '55134', 18359, 1, 
    '0', 'SOLICITUD PARA DEMANDA', '123453', 'JR', 'ialtamir', 
    TO_DATE('12/20/2017 13:27:30', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/20/2017 13:27:41', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, 
    NULL, 'ialtamir', NULL, NULL, 1, 
    1, NULL, NULL, NULL, NULL, 
    'Correcto ', NULL, NULL);

Insert into OPERACION.VMC_ETAPAS_TAREAS
   (ID_CASO, ID_TAREA, FECHA_REGISTRO, FECHA_FIN, ORIGEN, ID_PROC_VERIFICACION, JUICIO, ID_JUICIO, ID_ETAPA, ETAPA, NOMBRE_ETAPA, CREDITO, ID_ASIGNA, BANDEJA, FECHA_VERIFICADOR01, FECHA_FIN_VERIFICADOR01, FECHA_VERIFICADOR02, FECHA_FIN_VERIFICADOR02, FECHA_DICTAMEN, FECHA_FIN_DICTAMEN, ID_VERIFICADOR01, ID_VERIFICADOR02, ID_VERIFICADOR_DICTAMEN, RESULTADO_ETAPA_VER01, RAZON_ETAPA_VER01, RESULTADO_ETAPA_VER02, RAZON_ETAPA_VER02, RESULTADO_ETAPA_DICTAMEN, RAZON_ETAPA_DICTAMEN, COMENTARIO_VER01, COMENTARIO_VER02, COMENTARIO_DICTAMEN)
 Values
   (4313099, 1548, TO_DATE('12/20/2017 09:51:20', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    'QUANTUN', 39940, '78701', 78701, 0, 
    '0', 'ADAMANTINE II', '261934', 'BR', 'ialtamir', 
    TO_DATE('12/20/2017 10:26:09', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, NULL, NULL, 
    NULL, 'ialtamir', NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);

Insert into OPERACION.VMC_ETAPAS_TAREAS
   (ID_CASO, ID_TAREA, FECHA_REGISTRO, FECHA_FIN, ORIGEN, ID_PROC_VERIFICACION, JUICIO, ID_JUICIO, ID_ETAPA, ETAPA, NOMBRE_ETAPA, CREDITO, ID_ASIGNA, BANDEJA, FECHA_VERIFICADOR01, FECHA_FIN_VERIFICADOR01, FECHA_VERIFICADOR02, FECHA_FIN_VERIFICADOR02, FECHA_DICTAMEN, FECHA_FIN_DICTAMEN, ID_VERIFICADOR01, ID_VERIFICADOR02, ID_VERIFICADOR_DICTAMEN, RESULTADO_ETAPA_VER01, RAZON_ETAPA_VER01, RESULTADO_ETAPA_VER02, RAZON_ETAPA_VER02, RESULTADO_ETAPA_DICTAMEN, RAZON_ETAPA_DICTAMEN, COMENTARIO_VER01, COMENTARIO_VER02, COMENTARIO_DICTAMEN)
 Values
   (4106533, 200, TO_DATE('12/20/2017 10:09:18', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    'QUANTUM', 245783, '96387', 96387, 156, 
    '156', 'OFRECIMIENTO DE PRUEBAS', 'J21013', 'SR', 'GRUPO', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);




