   -- Crear Tabla  pendupm.GLTRAN con su indice
DROP TABLE pendupm.GLTRAN;

create table pendupm.GLTRAN as (
select *      
FROM GLTRAN@ERPBASE.COM A
);

CREATE INDEX PENDUPM.INDEX_BATBNR ON PENDUPM.GLTRAN
("BatNbr")
LOGGING
NOPARALLEL
COMPUTE STATISTICS;

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.GLTRAN TO PM_OPER;

GRANT DELETE, INSERT, SELECT, UPDATE ON PENDUPM.GLTRAN TO TL_PM;

