

ALTER TABLE PENDUPM.IAAL
 ADD (TAREAS_ABIERTAS  NUMBER(38));


ALTER TABLE PENDUPM.IAAL
 ADD (NM_TAREA_ABIERTA  VARCHAR(150));


DROP TABLE PENDUPM.TAREAS_BITACORA;

CREATE TABLE PENDUPM.TAREAS_BITACORA AS (
 SELECT IDGASTO, NMETAPA, COUNT(1) TOTAL_ABIERTAS FROM ( 
    SELECT  GM.IDGASTO, PB.NMETAPA, GM.FDFECREGISTRO, GM.FCSTATUS 
      FROM  PENDUPM.GASTOMAIN GM
INNER JOIN  PENDUPM.PLANDEVIAJEBITACORA PB
        ON  GM.IDGASTO = PB.IDGASTO
     WHERE  PB.FCRESULTADO IS NULL AND PB.FCCOMENTARIOS IS NULL   
  GROUP BY  GM.IDGASTO, PB.NMETAPA, GM.FDFECREGISTRO, GM.FCSTATUS
)
GROUP BY IDGASTO, NMETAPA
);


UPDATE PENDUPM.IAAL 
SET TAREAS_ABIERTAS = ( SELECT TOTAL_ABIERTAS FROM PENDUPM.TAREAS_BITACORA WHERE IDGASTO = PENDUPM.IAAL.IDGASTO );

UPDATE PENDUPM.IAAL 
SET TAREAS_ABIERTAS = 0
WHERE TAREAS_ABIERTAS IS NULL;

UPDATE PENDUPM.IAAL 
SET NM_TAREA_ABIERTA = ( SELECT NMETAPA FROM PENDUPM.TAREAS_BITACORA WHERE IDGASTO = PENDUPM.IAAL.IDGASTO )
WHERE TAREAS_ABIERTAS = 1;
