SELECT /*COUNT(DEL_INDEX), DEL_INDEX*/  * FROM pendupm.FACTURACIONBITACORA GROUP BY DEL_INDEX, IDGASTOMAIN 

SELECT COUNT(DEL_INDEX), DEL_INDEX, IDGASTOMAIN  FROM pendupm.FACTURACIONBITACORA GROUP BY DEL_INDEX, IDGASTOMAIN HAVING COUNT(*)> 1


SELECT * FROM pendupm.FACTURACIONBITACORA WHERE IDGASTOMAIN = 4310452 ORDER BY DEL_INDEX 