--FACTURACIONMAIN
--FACTURAASIGNACION
--FACTURACOMPROBA
-- 



Insert into PENDUPM.PRORRATEO_CUBO
   (ID_PRORRATEO, ID_CASO, PROCESO, ID_COMPROBACION, FCNOMINA, NMSOLICITANTE, FECHA_REGISTRO, FECHA_COMPROBACION, CREDITO, CARTERA, CENTRO_COSTOS, CUENTA_CONTABLE, CONCEPTO, IMPORTE, IMPORTE_IVA, CODIGO_IMPUESTO)
 Values
   (PENDUPM.SEQ_GASTO_PRORRATEO.NEXTVAL
   , 4296398
   , 'GASTO'
   , 124662
   , 'E000092'
   , 'RAMIREZ SANCHEZ ELDA HEVIA'
   , TO_DATE('11/04/2017 13:07:22', 'MM/DD/YYYY HH24:MI:SS')
   , TO_DATE('11/06/2017 13:07:22', 'MM/DD/YYYY HH24:MI:SS')
   , -- eXCEL 
   , (SELECT U1CARTERA FROM RCVRY.UDA1 WHERE U1ACCT  IN ('O205753'))
   , '110'
   , '6010010908'
   , 'REVISION OPINIONES DE VALOR'
   , -- excel importe 
   , 0
   , 0);
    
    
    
    -------------------------------------------------------------------------------------------------------
    
    
    Insert into PENDUPM.CARGA_PRORRATEOGASTO_PRE
   (ID_PRORRATEO, ID_CASO, PROCESO, ID_COMPROBACION, FCNOMINA, NMSOLICITANTE, FECHA_REGISTRO, FECHA_COMPROBACION, CREDITO, CARTERA, CENTRO_COSTOS, CUENTA_CONTABLE, CONCEPTO, IMPORTE, IMPORTE_IVA, CODIGO_IMPUESTO)
 Values
   (PENDUPM.SEQ_PRORRATEO_CUBO.NEXTVAL
   , 4296398
   , 'GASTO'
   , 124662
   , 'E000092'
   , 'RAMIREZ SANCHEZ ELDA HEVIA'
   , TO_DATE('11/04/2017 13:22:22', 'MM/DD/YYYY HH24:MI:SS')
   , TO_DATE('11/06/2017 13:07:22', 'MM/DD/YYYY HH24:MI:SS')
   , -- eXCEL
   , (SELECT U1CARTERA FROM RCVRY.UDA1 WHERE U1ACCT  IN ('O205753'))
   , '110'
   , '6010010908'
   , 'REVISION OPINIONES DE VALOR'
   , -- excel
   , 0
   , 0);
    
    
